service: alb-s3-sqs-es

plugins:
  - serverless-python-requirements
  - serverless-offline

package:
  individually: true

custom:
  pythonRequirements:
    dockerizePip: true
    invalidateCaches: true

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-2

functions:
  alb-s3:
    module: src
    handler: run.lambda_handler
