service: alb-s3-sqs-es

plugins:
  - serverless-python-requirements

package:
  individually: true
  include:
    - '!./**'
    - './src/**'
  exclude:
    - '**'

custom:
  pythonRequirements:
    dockerizePip: true
    invalidateCaches: true
    fileName: requirements.txt

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-southeast-2

functions:
  alb-s3:
    handler: src.run.lambda_handler
