service: cloudwatch-firehose-es

plugins:
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - '!./**'
    - './src/**'

custom:
  pythonRequirements:
    dockerizePip: true
    invalidateCaches: true
    fileName: requirements.txt

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-2
  lambdaHashingVersion: 20201221

functions:
  cloudwatch-firehose:
    handler: src/run.lambda_handler
